### ISSUE TITLE
Ability to pass a version parameter - feature request 

### ISSUE THREAD

**Issue by melezhik** [skaji/mi6#109]
Sometimes `mi6` has a wrong guess on the next version to be released, it'd be handy to pass instead a `--version` parameter to set a new release version for that cases.

Also I'd like to ask for `--noconfirm` parameter (or similar name) so that `mi6` would not ask a confirmation, will be useful for automation.

Thanks

**Comment by skaji** [comment]
Thanks. I will add the feature.

**Comment by melezhik** [comment]
Thank you!
