### ISSUE TITLE
Add dist.ini option to restrict recursive search for test files

### ISSUE THREAD

**Issue by tbrowder** [skaji/mi6#112]
Sometimes during development I want to restrict testing, so I either move files from my 't' directory to another directory at the same level or, between releases, move them to a subdirectory of the 't' directory.

In either case I would like to restrict mi6 from recursing below the 't' directory or inspecting other directories for test files.

**Comment by skaji** [comment]
mi6 test accepts arguments that are files or directories to be run.
So I don't think mi6 should have such option.

**Comment by tbrowder** [comment]
Sorry, you're correct. I'm closing this issue.
