### ISSUE TITLE
mi6 test doesn't use local version

### ISSUE THREAD

**Issue by coke** [skaji/mi6#113]
I have local uninstalled changes to my module.

using 'mi6 test' reports errors as if it's running my bin/ against the previously installed lib/

```zef test .``` works as expected

**Comment by lizmat** [comment]
I did not see that today when I did the first versions of the `hide-methods` distribution.  And that definitely was not installed locally yet.

**Comment by timo** [comment]
maybe setting `RAKUDO_MODULE_DEBUG=1` will give a hint or two

**Comment by skaji** [comment]
@coke Can you try `prove6 -l t`?

**Comment by skaji** [comment]
@coke ping?

**Comment by skaji** [comment]
No response. So close the issue.

**Comment by coke** [comment]
I have to recreate a situation where I expect this to fail, haven't had cycles yet. (the checkout I was using I've since installed the new version)

**Comment by coke** [comment]
Where is prove6?

**Comment by coke** [comment]
Using `prove6 -l t` does not use the version from lib (same as mi6)

**Comment by coke** [comment]
So, this issue is still open for me - 'zef test .' uses the local lib without me having to specify anything. `mi6 test` does not, and requires me to use `RAKULIB=lib`.

**Comment by coke** [comment]
```
$ raku --version
Welcome to Rakudo(tm) v2020.10-40-gccc50f7ae.
Implementing the Raku(tm) programming language v6.d.
Built on MoarVM version 2020.10-20-g70e3608cb.
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
$ zef list --installed 2> /dev/null | grep -i mi6
App::Mi6:ver<1.1.2>:auth<cpan:SKAJI>
```

**Comment by skaji** [comment]
`mi6 test` (and `TAP::Harness`) adds module search paths by `-IDIR`, not by environment variables.
So if you create a child process in your test by `run()` or something, it does not inherit module search paths from the parent process.

**Comment by coke** [comment]
I am testing a binary, so that does account for it. Would you consider changing to use the env var approach?

**Comment by skaji** [comment]
mi6 follows TAP::Harness.
