### ISSUE TITLE
Enable more unicode possibilities

### ISSUE THREAD

**Issue by tbrowder** [skaji/mi6#119]
Currently **mi6** recognizes the Github Markdown syntax for the Unicode Copyright symbol (in Raku: 'E<0c>') and converts it successfully. More such codes should be recognized, either through changes to **mi6** or an option to **mi6** to read a user's input file of such pairs.

Code conversions of immediate interest to me are three mathematical symbols:

Symbol name | Raku syntax | Github syntax
---                   | ---                  | ---
left floor          | E<0x230a>   | \&\#x230a\;
right fioor        | E<0x230b>   | \&\#x230b\;
middle dot       | E<0x22c5>   | \&\#x22c5\;

**Comment by skaji** [comment]
Converting pod to markdown is done by Pod::To::Markdown / HTML.
You may want to look at these modules.

**Comment by tbrowder** [comment]
Sorry, I should have known better.
