### ISSUE TITLE
Have the 'release' command include a 'build' step before the 'commit' step

### ISSUE THREAD

**Issue by tbrowder** [skaji/mi6#120]
After over a year of enjoying **App::Mi6** (thanks!),  I still find myself forgetting to run 'mi6 build' before running 'mi6 release'.

Having mi6 include a 'build' step before its 'commit' step would be helpful to me, and probably others, too. At the very least, having an option to do so in the 'dist.ini' file would be useful.

**Comment by skaji** [comment]
@tbrowder Thanks for bringing this up.
Does #121 work for you?

**Comment by tbrowder** [comment]
Thanks! I am almost ready to publish a new release and I will check this then, hopefully tomorrow.

**Comment by tbrowder** [comment]
The change works great--as expected, thanks!
