### ISSUE TITLE
Remove ver and auth from Module.rakumod

### ISSUE THREAD

**Issue by skaji** [skaji/mi6#126]
Currently, `mi6 new Module` generates `lib/Module.rakumod`, which contains

```
unit class Module:ver<0.0.1>:auth<cpan:SKAJI>;
```

The reason why I added ver and auth to Module.rakumod is that,
if you specify ver and auth to types, then end users can easily get Module's ver and auth in their code by

```
use Module;

say Module.^ver; # v0.0.1
say Module.^auth; # cpan:SKAJI
```

OTOH, at least in Module.rakumod itself, you can get ver and auth from `$?DISTRIBUTION.meta`.

I don't know how but if end users can get Module's ver and auth somehow,
I think we should remove ver and auth from Module.rakumod itself.

**Comment by tbrowder** [comment]
I'm okay with that as long as I can find it with zef, but I don't see that a user's code can determine the module's version and auth if it's not in the module. And I don't know if @tonyo is interested in taking care of that in fez.
