### ISSUE TITLE
[feature request] Enable mi6 to create a new Zef-compatible module

### ISSUE THREAD

**Issue by tbrowder** [skaji/mi6#134]
Better than converting from a CPAN-compatible mi6 module, the next step is to allow new mi6-created modules for Zef, thus encouraging module authors to move to the preferred repository for Raku modules.

**Comment by skaji** [comment]
You can try `mi6 new --zef Foo::Bar`.

**Comment by tbrowder** [comment]
Okay, sorry, I jumped the gun. Thanks.
