### ISSUE TITLE
Fez does not add the "zef:" prefix in the fez user config file as expected by App::Mi6

### ISSUE THREAD

**Issue by tbrowder** [skaji/mi6#135]
If the user adds it into the META6.json file, mi6 finds it doesn't agree with the fez configuration file.

**Comment by skaji** [comment]
What is the contents of

* (a) auth in META6.json
* (b) auth in Module.rakumod if any
* (c) un in ~/.fez-config.json

In my case https://github.com/skaji/raku-Acme-Test-Module-Zef

* (a) zef:skaji
* (b) N/A
* (c) skaji

**Comment by tbrowder** [comment]
+ (a) zef:tbrowder
+ (b) N/A
+ (c) tbrowder

**Comment by skaji** [comment]
> (b) N/A

Really?
Log message says Abbreviations.rakumod has cpan:TBROWDER

**Comment by tbrowder** [comment]
My bad, I got ahead of myself one more time and didn't see the end, sorry!  All is well.

**Comment by tbrowder** [comment]
One reason I wasn't watching closely is your statement that any 'auth' or 'ver' information there was ignored.
