### ISSUE TITLE
mi6 fails to run after the installation with the latest zef

### ISSUE THREAD

**Issue by titsuki** [skaji/mi6#14]
See the following error messages:
```
$ mi6 test
===SORRY!=== Error while compiling /home/itoyota/.rakudobrew/moar-nom/install/share/perl6/site/resources/19DFC05B99EC4E218A1A8D9A1B966919724DE593
Two terms in a row
at /home/itoyota/.rakudobrew/moar-nom/install/share/perl6/site/resources/19DFC05B99EC4E218A1A8D9A1B966919724DE593:1
------> @⏏ perl6 %~dpn0 %*
    expecting any of:
        infix
        infix stopper
        statement end
        statement modifier
        statement modifier loop
```

My zef version is:
https://github.com/ugexe/zef/commit/fa5d8207702d292ea9c356297c2df45ba7490e44

**Comment by titsuki** [comment]
My environment is Debian jessie, not Windows.

**Comment by treyharris** [comment]
@titsuki  FYI, a workaround for now (courtesy timotimo on #perl6):

1. `git clone skaji/mi6; cd mi6`
1. `rm bin/mi6.bat`
1. `zef install --force .`

**Comment by titsuki** [comment]
@treyharris 
Thanks for your replay !
I noticed that too today and directly overwrote the pre-compiled file (i.e. `19DFC05B99EC4E218A1A8D9A1B966919724DE593`) , but your solution seems better than I did.

**Comment by skaji** [comment]
@titsuki @treyharris thanks. I've removed the bat file.
