### ISSUE TITLE
CI build fails

### ISSUE THREAD

**Issue by melezhik** [skaji/mi6#148]
Hi! 

Report - http://sparrowhub.io:2222/report/218

HTH

all the best

Aleksei

**Comment by melezhik** [comment]
Hi! May I ask you why you consider the issue is closed? Thanks

**Comment by skaji** [comment]
If you believe mi6 has a bug,
please describe it here in details and provide steps to reproduce it.

**Comment by melezhik** [comment]
I guess steps are clearly visible at the report link attached, did you check it out?

**Comment by melezhik** [comment]
@tbrowder  underneath this is `zef install --deps-only --test-depends --/test .  && racoco -l --html`

**Comment by melezhik** [comment]
started new discussion , looks like this fails only when runs with RaCoCo - https://github.com/atroxaper/raku-RaCoCo/issues/12

**Comment by atroxaper** [comment]
It have been fixed in App::RaCoCo v1.6.0.
https://github.com/atroxaper/raku-RaCoCo/releases/tag/v1.6.0
