### ISSUE TITLE
Unable to use App::Mi6 with a module with a hyphenated name

### ISSUE THREAD

**Issue by tbrowder** [skaji/mi6#149]
I have an existing, published module (currently on CPAN) named "AVL-Tree" (not "AVL::Tree") and am trying to convert it to be managed by mi6.

I have so far been unable to get mi6 to recognize the module in its current form with the hyphen. Note I can successfully use "zef test ." for the module as it exists.

The module's repo is at [github.com/tbrowder/AVL-Tree](https://github.com/tbrowder/AVL-Tree.git).

**Comment by skaji** [comment]
If you set name manually in dist.ini,
then it works, I guess.

See, for example,
https://github.com/lizmat/shorten-sub-commands/blob/main/dist.ini

**Comment by tbrowder** [comment]
I was finally able to use it with no problems. Somehow I was getting some strange errors from my zef store.  Thanks for your patience. Closing this issue as not valid.
