### ISSUE TITLE
Mi6 should handle the license field of META6.json

### ISSUE THREAD

**Issue by samcv** [skaji/mi6#15]
Currently it doesn't handle it, or automatically set it (it does automatically create a LICENSE file for Artistic 2.0 though)

**Comment by skaji** [comment]
Thanks. Is there a document or a spec for META6.json I should refer to?

**Comment by samcv** [comment]
See: https://design.perl6.org/S22.html#license

The spec has been solidified recently. Previously S22 said that it should have a URL to the license, but that was not useful when we get the ability for package managers to black/whitelist modules etc, so we use SPDX specifiers.

Also see the top section here: https://github.com/perl6/ecosystem/issues/324

Where I describe a few other things.

**Comment by skaji** [comment]
https://design.perl6.org says:
```
Note: these documents may be out of date. For Perl 6 documentation see docs.perl6.org; for specs, see the official test suite.
```
Do I safely refer to it anyway:)

**Comment by samcv** [comment]
This may be helpful as well, and is in a PR i have with Test::META, don't know when or if that will be approved, but it may be helpful for you https://github.com/samcv/Test-META/blob/license/lib/Test/META/LicenseList.pm6

**Comment by samcv** [comment]
@skaji at least the license section is up to date, since I rewrote it just this week :-D

**Comment by samcv** [comment]
Awesome! Thank you!
