### ISSUE TITLE
Make option "--zef" the default for newly created modules

### ISSUE THREAD

**Issue by tbrowder** [skaji/mi6#151]
The community is trying to get all Raku modules to be published in the Zef ecosystem. This module should make "--zef" the default for newly created modules. There should be no concern about deprecation.

**Comment by skaji** [comment]
Yeah, that's the plan.

**Comment by tbrowder** [comment]
Or, maybe better for backward compatibility, require the user specify either '--zef' or  '--cpan' with option 'new'.
