### ISSUE TITLE
Have mi6 fail if not in a directory containing file 'dist.ini'

### ISSUE THREAD

**Issue by tbrowder** [skaji/mi6#156]
I have more than once blindly used 'mi6 test' in a module base directory only to have mi6 silently corrupt my existing README.md file because it isn't currently managed with mi6.

Consider that as a compliment on how using the wonderful mi6 is so ingrained  with my muscle memory and please fix this problem.

Thanks.

**Comment by skaji** [comment]
dist.ini is optional.

**Comment by tbrowder** [comment]
Is there any other way to prevent such an accident?

**Comment by skaji** [comment]
Unfortunately no.

**Comment by tbrowder** [comment]
Thanks, but if it were up to me, I would use **dist.ini** as an mi6 marker.
