### ISSUE TITLE
Ensure files in the module's 'resources' directory are duplicated in its 'META6.json' file

### ISSUE THREAD

**Issue by tbrowder** [skaji/mi6#159]
Making it a part of the mi6 build step might be a start.

**Comment by skaji** [comment]
Please put resources in META6.json by yourself.

The reason mi6 does not manage "resources" in META6.json is that
some resources may not be tracked by git.

For example, "libraries.json" of openssl distribution is generated in build phase.
https://github.com/sergot/openssl/blob/main/META6.json#L36
