### ISSUE TITLE
Need to allow for submitting pull requests for other authors

### ISSUE THREAD

**Issue by tbrowder** [skaji/mi6#180]
When using mi6 on a PR, there is sometimes a conflict in the README badge code by referring to the PR author/repo and not the real author/repo.

In my experience, this has happened when the original author was **not** using mi6 (dist.ini not present) and I was creating a PR to convert the receiving repo to use mi6.

Instructions on how to handle that situation would be very useful. Perhaps the recipient would have to be willing to make changes on his or her end before the PR was submitted.

**Comment by skaji** [comment]
Thanks for the report.
Does #181 work for you?
