### ISSUE TITLE
shouldn't a MANIFEST be created for the tarballs?

### ISSUE THREAD

**Issue by ufobat** [skaji/mi6#22]
I just created a tarbal with mi6. I realized that it doesn't contain a MANIFEST. shouldnt it?

**Comment by skaji** [comment]
@ufobat If you have any thoughts, please add comments below.
https://github.com/perl6/modules.perl6.org/commit/f1af625ae4c2806d3be79821f75af28f6270d62c

**Comment by skaji** [comment]
mi6 will emit a MANIFEST file once perl6 community agree that distributions must have MANIFEST files.

I close this ticket for now.
