### ISSUE TITLE
README.md generataion should not happen automatically

### ISSUE THREAD

**Issue by ufobat** [skaji/mi6#23]
I want to use mi6 to build the tarballs to upload them to pause.cpan.org. Unfortunately it is quite complicated regarding the README.md handling.

I need to reverte the changes to the README.md after the mi6 dist command. Then I need to copy the changes into the folder and rebuild the tarball manually.

1) README.md generation should only happen if it is requested with a command

in addition:
2) README.md generation makes assumptions which can not be overriden with some command line switches. e.g whether I want to have a travis.ci header or not, which file should be converted to README.md, maybe it makes even sense to convert more then one pm6 file to markdown.

**Comment by skaji** [comment]
It could be nice that mi6 allows you have a configuration file, in which you explicitly disables regenerating README.

**Comment by ufobat** [comment]
what about either
`mi6 dist --keep-readme`
`mi6 build --keep-readme`
or
merging #3 and then
`mi6 build-readme && mi6 build`?

I would write a PR if you like :)

**Comment by skaji** [comment]
Do you really like `--keep-readme` option?
It is easy to imagine that you sometimes forget to add that option to `mi6 build`.

**Comment by ufobat** [comment]
I am happy for any working sulution :+1: 
Personally i'd prefere merging #3 and `mi6 build-readme && mi6 build` over `--keep-readme` over having a config file.

**Comment by skaji** [comment]
> Personally i'd prefere merging #3 and mi6 build-readme && mi6 build over --keep-readme over having a config file.

#3 is just to add a build-readme command. So even after merging #3,  `mi6 build` regenerates README anyway.

**Comment by skaji** [comment]
Note that I will not change the behavior (regenerating README) of `mi6 build`.
On the other hand, it may be possible to change the behavior by some command line options or some configuration files.

**Comment by skaji** [comment]
I respect Perl5/6's pod feature.

**Comment by ufobat** [comment]
would you accept a `--keep-readme` option for your commands? in that case i'll write a PR asap
