### ISSUE TITLE
`mi6 dist` nukes README.md content

### ISSUE THREAD

**Issue by zoffixznet** [skaji/mi6#25]
Trying to run it [with this dist](https://github.com/zoffixznet/perl6-Number-Denominate/tree/7b1329ef853745be396f5ea90facea6551f45dfe) and it deletes all of the existing README.md content and replaces it with just the travis badge.

**Comment by skaji** [comment]
thanks. I will look into it.

**Comment by skaji** [comment]
mi6 regenerates README.md from the pod in the main module file.

**Comment by zoffixznet** [comment]
Ah, OK, then the issue is subsumed by #23

Thanks.
