### ISSUE TITLE
Is it possible to remove package directories and tarballs _after_ mi6 upload?

### ISSUE THREAD

**Issue by melezhik** [skaji/mi6#31]
Hi!

This is rather a suggestion then issue. But it could be very useful.  Now after `mi6 upload` finishes it leaves directories and archives ( like for distribution named `Foo` it would be a directory `Foo-$version/` and archive `Foo-$version.tar.gz` ). Is it possible to have an option to clean thus stuff? 

Thanks

**Comment by skaji** [comment]
@melezhik Thanks and sorry for the late follow-up.
Fixed in 707c4d9 and released https://www.cpan.org/authors/id/S/SK/SKAJI/Perl6/App-Mi6-0.1.5.tar.gz

**Comment by melezhik** [comment]
Thank you!

On Mar 16, 2018 7:05 PM, "Shoichi Kaji" <notifications@github.com> wrote:

@melezhik <https://github.com/melezhik> Thanks and sorry for the late
follow-up.
Fixed in 707c4d9
<https://github.com/skaji/mi6/commit/707c4d9797d29a4420f160a032f25f21bc00643c>
and released https://www.cpan.org/authors/id/S/SK/SKAJI/Perl6/App-Mi6-0.
1.5.tar.gz

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/skaji/mi6/issues/31#issuecomment-373876320>, or mute
the thread
