### ISSUE TITLE
Could the BumpVersion test be extended to grammars (and maybe roles) as well?

### ISSUE THREAD

**Issue by drforr** [skaji/mi6#33]
When releasing Module::Name, it seems that Module/Name.pm6 must contain a class to attach a version to. Could this test be extended to match against a grammar as well? I have several modules whose entire content will simply be a grammar, and I don't believe these will pass the 'mi6 release' checks as written.

**Comment by skaji** [comment]
Thanks. Released a new version 0.1.3 to CPAN.
Once zef index it, you can install it by `zef install App::Mi6`.

**Comment by drforr** [comment]
Thanks! The module already makes releasing stuff to CPAN simple, this bug fix makes it even better!
