### ISSUE TITLE
Changes file not being correctly validated?

### ISSUE THREAD

**Issue by drforr** [skaji/mi6#35]
I have a Changes file for Perl6::Tidy (posted in its entirety below). When I run 'mi6 release' I get the following message:

--cut here--
==> Step 1. CheckChanges
Changes file does not have the next release description.
--cut here--

Contrary to the warning, 0.0.2 *is* the next release, as set in META6.json. The offending line appears to be:

--cut here--
    if $content !~~ /^^ '{{$NEXT}}' \n+ <[\ \t]>+ \S/ {
        die "Changes file does not have the next release description.\n";
    }
--cut here--

I think the RE is incorrect, and it should read (changng <[\ \t]>+ to <[\ \t]>*, because in the sample change entry there is no whitespace between the timestamp and the start of the line):

--cut here--
    if $content !~~ /^^ '{{$NEXT}}' \n+ <[\ \t]>* \S/ {
        die "Changes file does not have the next release description.\n";
    }
--cut here--

And again, thanks. I have some ideas on how to make it even more useful, but those will have to wait until I get the backlog of modules released...

--cut here--
Revision history for Perl6-Tidy

{{$NEXT}}

0.0.2  2018-03-13T14:50:39+01:00
    - Add Perl6::Parser to dependencies

0.0.1  2018-03-12T16:17:39+01:00
    - Initial version
--cut here--

**Comment by skaji** [comment]
You do **NOT** need to write `0.0.2 2018-03-13T14:50:39+01:00` by yourself.
(Nor do you need to write `class Perl6::Tidy:ver<0.0.2>` in pm file)
mi6 will take care of them.

If you want to release a new version, first write the next release description so that `Changes` file looks like:
```
Revision history for Perl6-Tidy

{{$NEXT}}
    - Add Perl6::Parser to dependencies

0.0.1  2018-03-12T16:17:39+01:00
    - Initial version
```
And execute `mi6 release`.

**Comment by drforr** [comment]
Aha, thank you for clarifying. I'm guessing now that I've read a bit more that 'mi6 build' is what I'm after, I naively assumed that 'mi6 release' was handling most of the process. I'll roll back and update appropriately.
