### ISSUE TITLE
Could the BumpVersion step check the "next release version" input for valid format?

### ISSUE THREAD

**Issue by drforr** [skaji/mi6#36]
==> Step 4. BumpVersion
Next release version? [0.0.2]:
--cut here--

Long story short: I reflexively entered 'y' to the prompt and as a consequence now have a version 'y' floating around that I really did *not* intend to create. I suppose it's possible that someone may want a non-numeric version number (Unicode digits or something similar, maybe...) so something like:

--cut here--
Next release version? [0.0.2]: y
Are you sure you meant to use 'y' as a version number? [yes/N]:
--cut here--

forcing the user to type 'yes' to override the setting would be a perfectly reasonable action to take, at least in my mind. Also, if someone is automating this by piping 'yes' to it, something else will happen :)

**Comment by skaji** [comment]
Thanks. Released https://www.cpan.org/authors/id/S/SK/SKAJI/Perl6/App-Mi6-0.1.4.tar.gz

**Comment by drforr** [comment]
Now *that* is service. Thanks, I know it's a mistake that shouldn't happen, but I figure if I've made it...
