### ISSUE TITLE
The META6.json template doesn't have auth field

### ISSUE THREAD

**Issue by titsuki** [skaji/mi6#37]
This template has authors field but doesn't have auth field.
I think auth field potentially has higher importance than authors field because it can be used for module identification.

**Comment by skaji** [comment]
So do you expect mi6 fill `cpan:AUTHOR` as auth?

**Comment by titsuki** [comment]
@skaji Yes, I do. I think auth field should default to `cpan:AUTHOR`.

**Comment by skaji** [comment]
@titsuki Released a new version to CPAN!
You will install it by `zef upgrade App::Mi6` soon.

**Comment by titsuki** [comment]
Thanks a lot!
