### ISSUE TITLE
Want Distclean to move the tar file in a "releases" directory

### ISSUE THREAD

**Issue by lizmat** [skaji/mi6#41]
I would like to have the Distclean step to move the generated tar file into a subdirectory "releases" so that you would have a local copy of what you released to CPAN for future reference, instead of having it just nuked.

**Comment by lizmat** [comment]
> On 11 Apr 2018, at 15:13, Shoichi Kaji <notifications@github.com> wrote:
> You can use —keep option.

aha!  Didn’t find that in the doc  :-(

**Comment by skaji** [comment]
@lizmat Released a new version 0.1.7 to CPAN,
where you will find documentation about `--keep` in `mi6 help`.

**Comment by lizmat** [comment]
Thank you!
