### ISSUE TITLE
Consider encoding :: as -- instead of -

### ISSUE THREAD

**Issue by ugexe** [skaji/mi6#47]
`package Foo-Bar { }` ok
`package Foo--Bar { }` not ok

Because of the above there is no problem with guessing if a `--` is meant to actually be` --` or `::` when round tripping names. This means it is safe to `s/::/--/` `s/--/::/` to allow valid `Foo-Bar` style namespaces.

**Comment by skaji** [comment]
I see your point,
but `--` looks odd to me.
So I don't change the current behavior.
