### ISSUE TITLE
Cannot "mi6 release" my module

### ISSUE THREAD

**Issue by lizmat** [skaji/mi6#49]
https://github.com/lizmat/Acme-_-

It's really a test of using unicode codepoints in module names.

All seems fine, until the `mi6 build` step alters the META6.json, e.g.:

  "provides" : {
    "Acme::ಠ_ಠ" : "lib/Acme/ಠ_ಠ.pm6"
  },

to:

  "provides" : {
    "Acme::\u0ca0_\u0ca0" : "lib/Acme/\u0ca0_\u0ca0.pm6"
  },

and then the building of the tar file goes wrong.

I know this module is silly, but it is a good test  :-)

**Comment by skaji** [comment]
Is there document that defines which characters in pm filenames are valid?

**Comment by lizmat** [comment]
I think Rakudo Perl 6 allows anything that is a valid identifier in Unicode?

**Comment by skaji** [comment]
I think there are file systems  that do not allow Unicode filenames.

**Comment by lizmat** [comment]
That’s true.  But that’s fewer and fewer.

I mean: if we really want to be compatible, we should only use uppercase filenames in 8.3 format.  :-)

My point is: on my filesystem I can create the tar file, and I’m pretty sure I can upload it fine to PAUSE.  It’s a step in App::mi6 that’s preventing me to do that  :-(

**Comment by skaji** [comment]
I will answer this isuue tonight (JST).

**Comment by skaji** [comment]
While I deeply respect Perl5's ecosystem around CPAN, I must say it is too tolerant  and complicated.
I want ecosystem of Perl6 to become as *simple* as possible.

**Comment by skaji** [comment]
I close this issue.
