### ISSUE TITLE
Suggestion: Add Test::META to the build requirements

### ISSUE THREAD

**Issue by drforr** [skaji/mi6#50]
Best practices seem to include a t/META.t file in released distributions, so adding Test::META to your build META6.json file might save module authors a step.

**Comment by skaji** [comment]
I'm not sure including a t/META.t file in *released* distributions is one of best practices.
Instead, I think authoring tools (eg: mi6) should validate META6.json.

**Comment by drforr** [comment]
Fair enough. Besides, the modules might change and your module could silently fall out of sync. Closing the suggestion.
