### ISSUE TITLE
"release" packages symlinks as files.

### ISSUE THREAD

**Issue by lembark** [skaji/mi6#51]
Testing code that handles symlinks. Several t/*.t files are symlinks, but they are released as content not symlinks, which breaks the tests.

Q: Is there any way to release them as links?

**Comment by skaji** [comment]
@lembark Thanks for reporting this. I will look into it.

**Comment by skaji** [comment]
I don't have a plan to support symlinks,
and I'm not sure symlinks are portable.
So close this issue.
