### ISSUE TITLE
Colors are hard to read on light background

### ISSUE THREAD

**Issue by jmaslak** [skaji/mi6#56]
I have a hard time reading the note text on a light colored background - here's a sample from my term window:

![image](https://user-images.githubusercontent.com/673827/46263020-dae7e780-c4c6-11e8-8fd9-90f0b1a13bd4.png)

I'd like to work on this and make it configurable.  Do you have a preferred way of configurating this?  I was thinking that it could be configured either by some sort of environmental variable or a ~/.mi6 config file.  I'm initially only thinking of a setting that switches between LIGHT, DARK, and NONE.  The default would be LIGHT on non-Windows (the light green) and NONE on Windows (no ANSI codes).  But if you have a preferred approach, I'd prefer to implement it that way.

**Comment by skaji** [comment]
For the time being, please set NO_COLOR=1.
