### ISSUE TITLE
guessing user and repo for building README.md

### ISSUE THREAD

**Issue by ufobat** [skaji/mi6#60]
I've recently renamed my remote git repositories, they're not in a different alphabetically order. That causes that the README.md now gets generated with the wrong travis-ci $user. Woudn't it be nice if this can be configured or "defined" in a more deterministic way?

**Comment by skaji** [comment]
If you update git remote, mi6 would follow that.

**Comment by ufobat** [comment]
I've got 2 remotes. The original repository is the jasonmay/perl6-ioc. I've got the commit-bit on this repository as well. And I am the one making the releases on CPAN.

```
> git remote -v
origin	https://github.com/ufobat/perl6-ioc.git (fetch)
origin	https://github.com/ufobat/perl6-ioc.git (push)
upstream	https://github.com/jasonmay/perl6-ioc.git (fetch)
upstream	https://github.com/jasonmay/perl6-ioc.git (push)
```

**Comment by skaji** [comment]
I see.
mi6 should use "origin" by default.

It might be helpful to add option to change it.
