### ISSUE TITLE
mi6 release without cpan upload

### ISSUE THREAD

**Issue by ufobat** [skaji/mi6#62]
Is it supposed to make a `mi6 release` without uploading it to CPAN automatically?
Because if you say `no` to that step, all the further steps are cancled and you Changes file does not get updated. Basically the same applies if you do not want to make the `git push` with mi6.

**Comment by skaji** [comment]
If mi6 supports the following configuration, does this work for you?
```ini
; dist.ini
[Release]
upload-to-cpan = false
git-push = false
```

**Comment by ufobat** [comment]
I think your suggestion regarding the configuration is good and would certainly help me and maybe others.

But the point of the ticket was that saying `no` to the cpan-upload step does not only mean that you wont upload it to cpan but you would also abort the `mi6 release`.

**Comment by skaji** [comment]
What do you want mi6 to do by release command?

**Comment by ufobat** [comment]
I would hope that saying `no` to the cpan-upload-step would continue all further steps, except step `CleanDist` since you probably still want to upload the file manually to pause.

Same for not having the git-pushes. I want to review the changes in my local repository and then do the `git push` manually.

**Comment by tbrowder** [comment]
Those changes would make mi6 useful for private module development--especially if the release could just use zef to install locally and commit the changes and other thing to the local repo only.

**Comment by ufobat** [comment]
Have you decided on this issue?

**Comment by skaji** [comment]
I don't have a plan to support this anytime soon.
So closing this issue.
