### ISSUE TITLE
A `print` in an `END` phaser messes up the META6.json file.

### ISSUE THREAD

**Issue by kuerbis** [skaji/mi6#71]
cat lib/Hallo.pm6

    use v6;
    unit class Hallo:ver<0.0.1>;

    END { print "\e[0J" }

    method run {
        say "Hallo";
    }

META6.json bevore `mi6 build`:

    {
      "authors" : [
        "kuerbis"
      ],
      "build-depends" : [ ],
      "depends" : [ ],
      "description" : "",
      "license" : "Artistic-2.0",
      "name" : "Hallo",
      "perl" : "6.c",
      "provides" : {
        "Hallo" : "lib/Hallo.pm6"
      },
      "resources" : [ ],
      "source-url" : "",
      "tags" : [ ],
      "test-depends" : [ ],
      "version" : "0.0.1"
    }

META6.json after `mi6 build`:

    {
      "auth" : "\n\u001b[0J",
      "authors" : [
        "kuerbis"
      ],
      "build-depends" : [ ],
      "depends" : [ ],
      "description" : "",
      "license" : "Artistic-2.0",
      "name" : "Hallo",
      "perl" : "6.c",
      "provides" : {
        "Hallo" : "lib/Hallo.pm6"
      },
      "resources" : [ ],
      "source-url" : "",
      "tags" : [ ],
      "test-depends" : [ ],
      "version" : "0.0.1\n\u001b[0J"
    }

**Comment by skaji** [comment]
I don't think mi6 should take care of such case.
