### ISSUE TITLE
Problem with a distribution lacking its "base module"

### ISSUE THREAD

**Issue by frithnanth** [skaji/mi6#84]
I'm working on a distribution whose name is Math::Libgsl.
There's no actual Math::Libgsl module, but a dozen of modules with names such as Math::Libgsl::Constants, Math::Libgsl::Elementary, etc.

When I issue the `mi6 build` command, it modifies the META6.json file and changes the `"name"` tag, picking a random name among the list of modules.

Is there a cleaner solution other than adding an empty Math::Libgsl module?

**Comment by skaji** [comment]
> Is there a cleaner solution other than adding an empty Math::Libgsl module?

No.
