### ISSUE TITLE
Doesn't support files with multiple classes

### ISSUE THREAD

**Issue by Leont** [skaji/mi6#85]
Mi6 doesn't support putting more than one class (or another type) into one enum. Any such classes will end up missing from the provides field. There's also no way to disable the regeneration of this provides field as a stopgap.

**Comment by skaji** [comment]
Is there a way to get classes programmably  declared in a certain file?

**Comment by skaji** [comment]
>  There's also no way to disable the regeneration of this provides field as a stopgap.

If mi6 supports the following configuration, does it work for you?
```ini
[MetaProvides]
enabled = false
```

**Comment by Leont** [comment]
> If mi6 supports the following configuration, does it work for you?

Yeah that would be a helpful workaround (assuming it leaves the existing provides field alone), as it would allow me to at least get a correct provides field.

**Comment by Leont** [comment]
> Is there a way to get classes programmably declared in a certain file?

Not that I'm aware of. What we'd want is the equivalent of `Module::Metadata`. I would guess Perl6::Parser would be a good foundation for building such a thing.

**Comment by softmoth** [comment]
It seems that App::Mi6 similarly does not handle `provides` outside of `lib`; for example, this unwanted change:

```diff
--- a/META6.json
+++ b/META6.json
@@ -15,7 +15,6 @@
   "perl" : "6.d",
   "provides" : {
     "Pod::Cache" : "lib/Pod/Cache.rakumod",
-    "rakudoc" : "bin/rakudoc",
     "Rakudoc" : "lib/Rakudoc.rakumod",
     "Rakudoc::CMD" : "lib/Rakudoc/CMD.rakumod"
   },
```

Is `[MetaProvides] enabled = false` available?

**Comment by softmoth** [comment]
No, it's not. I may well be mistaken. I'll look into it more.

**Comment by skaji** [comment]
Closed by https://github.com/skaji/mi6/pull/141
