### ISSUE TITLE
Mi6 needs to produce a zip file for releases

### ISSUE THREAD

**Issue by tbrowder** [skaji/mi6#87]

**Comment by skaji** [comment]
I'm not sure mi6 needs to produce zip files.

**Comment by tbrowder** [comment]
On Fri, Apr 10, 2020 at 19:06 Shoichi Kaji <notifications@github.com> wrote:

> I'm not sure mi6 needs to produce zip files.
>

When I was first publishing Raku modules back in early 2016, I was told to
produce both tgz and zip files. When you manually create a realease on
Github, it creates both a tgz and a zip file.

**Comment by skaji** [comment]
I respect your workflow,
but I don't think mi6 needs to produce zip files.
