### ISSUE TITLE
upload to cpan on windows does not work

### ISSUE THREAD

**Issue by ufobat** [skaji/mi6#95]
I am not yet sure why this error happens. but `mi6 release` on my Windows 10 box failes due to a HTTP::Tinyish problem.

I've found this issue as well: https://github.com/skaji/perl6-CPAN-Uploader-Tiny/issues/1 . Maybe this is releated somehow.

```
==> Step 7. MakeDist
==> Step 8. UploadToCPAN
Are you sure you want to upload Time-Crontab-1.0.0.tar.gz to CPAN? (y/N) y
Failed to remove the file 'C:\Users\marti\AppData\Local\Temp\01tKRiYYam': Failed to delete file: 6
  in method request at C:\rakudo\share\perl6\site\sources\6147EE1DB4B8D3C3F226274E1CCF334A31858A03 (HTTP::Tinyish::Curl) line 55
  in method <anon> at C:\rakudo\share\perl6\site\sources\5FE7856C6FE71818233BDDF4C956EE948B2C292F (HTTP::Tinyish::Base) line 7
  in method upload at C:\rakudo\share\perl6\site\sources\741E5FA40BFDD9F3C19B02B55D01F8557B2950FC (CPAN::Uploader::Tiny) line 92
  in method run at C:\rakudo\share\perl6\site\sources\C3031C13678DE1EDC79338CBF2ED445050100713 (App::Mi6::Release::UploadToCPAN) line 25
  in method run at C:\rakudo\share\perl6\site\sources\47EE91C3740E02E8A5C7DA63A1FC7D25CC89FB33 (App::Mi6::Release) line 65
  in method cmd at C:\rakudo\share\perl6\site\sources\70AC13768D0B421C619B4CBD4DBDECD0642F675B (App::Mi6) line 91
  in sub MAIN at C:\rakudo\share\perl6\site\resources\EF9CD605C74542F759FD6EB1AADBDBEB07A14DA4 line 21
  in block <unit> at C:\rakudo\share\perl6\site\resources\EF9CD605C74542F759FD6EB1AADBDBEB07A14DA4 line 6
  in sub MAIN at C:\rakudo\share\perl6\site\bin\mi6 line 3
  in block <unit> at C:\rakudo\share\perl6\site\bin\mi6 line 1
```

**Comment by juliodcs** [comment]
Hi,

I'm having the same problem. 

    Using App::Mi6 version v1.0.3
    and Rakudo: 2020.05.1
    Windows 10

Curl can be located on PATH:

Curl version:

    curl 7.55.1 (Windows) libcurl/7.55.1 WinSSL

The strage thing here is that the module is correctly uploaded to CPAN. However, It is just the temporal file deletion that fails.

I can manually delete the file, though. No process is locking it in any way.

This is the content of the file:

    HTTP/1.0 200 OK
    Content-Length: 9731
    Cache-Control: no-cache
    Accept: *
    Content-Type: text/html;charset=UTF-8
    Pragma: no-cache
    Date: Mon, 14 Sep 2020 17:32:43 GMT
    Connection: close

**Comment by skaji** [comment]
Closing in favor of #146
