### ISSUE TITLE
"mi6 build" adds pod of Pod::To::Markdown to README.md

### ISSUE THREAD

**Issue by lizmat** [skaji/mi6#96]
And because "build" is part of the release process, it screws up the READM.md "on the way out" so to speak.

Case in point: https://modules.raku.org/dist/Hash2Class:cpan:ELIZABETH  Compare this to the contents of: https://modules.raku.org/dist/Hash2Class:cpan:ELIZABETH/lib/Hash2Class.pm6#L450

**Comment by skaji** [comment]
Thanks.

"mi6 build" executes

```
RAKULIB=$PWD/lib raku --doc=Markdown lib/Hash2Class.pm6
```

to render markdown.

So this is an issue for Pod::To::Markdown.

**Comment by skaji** [comment]
There are 5 Pod::To::HTML, and I suspect "unexpected" Pod::To::HTML was installed.
```
❯ zef search  Pod::To::HTML
===> Found 5 results
-----------------------------------------------------------------------------------------------------------------------
ID|From                             |Package                                             |Description
-----------------------------------------------------------------------------------------------------------------------
0 |Zef::Repository::Ecosystems<p6c> |PodCache::Module:ver<0.3.1>:auth<Richard Hainsworth>|Render pod files from a ca...
1 |Zef::Repository::Ecosystems<p6c> |Raku::Pod::Render:ver<2.3.1>:auth<github:finanalyst>|A generic Pod Renderer for ..
2 |Zef::Repository::Ecosystems<p6c> |Pod::To::HTML:ver<0.7.0>:auth<github:Raku>          |Convert Raku Pod to HTML
3 |Zef::Repository::Ecosystems<cpan>|Pod::To::HTML::Section:ver<0.1.0>:api<0>            |Convert a Pod6 document to ..
4 |Zef::Repository::Ecosystems<cpan>|Pod::To::HTMLBody:ver<0.0.1>:auth<github:drforr>    |HTML body
-----------------------------------------------------------------------------------------------------------------------

**Comment by skaji** [comment]
Pod::To::Markdown expect `Pod::To::HTML:ver<0.7.0>:auth<github:Raku>`,
but you installed `Pod::To::HTML:auth<github:finanalyst>`.

**Comment by lizmat** [comment]
$ zef uninstall Pod::To::HTML
!!!> Found no matching candidates to uninstall
$ zef install Pod::To::HTML
All candidates are currently installed
No reason to proceed. Use --force-install to continue anyway

*sigh*

**Comment by skaji** [comment]
https://github.com/softmoth/perl6-pod-to-markdown/pull/21

**Comment by skaji** [comment]
The fix have been merged into perl6-pod-to-markdown.
I think we can close this issue.
