### ISSUE TITLE
Tests always come back failed, but "mi6 test" is clean

### ISSUE THREAD

**Issue by lizmat** [skaji/mi6#98]
The latest version of `App::Mi6` appears to add a `.github/workflows/test.yml`, which is great.

However, none of the tests come out clean for me, where `prove6 -l t` *does* run clean locally.

Am I missing something?  Is there something amiss in the ecosystem?

Example link: https://github.com/lizmat/API-Discogs/actions/runs/183154645

**Comment by skaji** [comment]
The action in the example link fails in actions/checkout@v2 step, which seems to be a github action platform issue.

**Comment by skaji** [comment]
```
error: invalid path 't/client/database/search?q=nirvana.json'
```

The filename of `'t/client/database/search?q=nirvana.json'` may be invalid on windows.

**Comment by lizmat** [comment]
Ok that seems to help for the Ubuntu case.  The Windows case here seems to die on installing App::Prove:

    ===> Searching for: App::Prove6
    37
    Terminate batch job (Y/N)? 

https://github.com/lizmat/API-Discogs/runs/911843185

Perhaps it's taking too long?

**Comment by skaji** [comment]
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
GitHub defaults to cancel all in-progress jobs if any matrix job fails.

Macos job fails, so windows job cancels.

**Comment by skaji** [comment]
I suspect the cause of the test failure of macos is OpenSSL module.

**Comment by skaji** [comment]
If you use the absolute path for libraries, then OpenSSL module will work.
```diff
diff --git lib/OpenSSL/NativeLib.pm6 lib/OpenSSL/NativeLib.pm6
index 4316bf1..704c4f1 100644
--- lib/OpenSSL/NativeLib.pm6
+++ lib/OpenSSL/NativeLib.pm6
@@ -4,18 +4,21 @@ sub ssl-lib is export {
     state $lib = $*DISTRO.is-win
         ?? dll-resource('ssleay32.dll')
         !! $*VM.platform-library-name('ssl'.IO).Str;
+    "/usr/local/opt/openssl@1.1/lib/$lib";
 }

 sub gen-lib is export {
     state $lib = $*DISTRO.is-win
         ?? dll-resource('libeay32.dll')
         !! $*VM.platform-library-name('ssl'.IO).Str;
+    "/usr/local/opt/openssl@1.1/lib/$lib";
 }

 sub crypto-lib is export {
     state $lib = $*DISTRO.is-win
         ?? dll-resource('libeay32.dll')
         !! $*VM.platform-library-name('crypto'.IO).Str;
+    "/usr/local/opt/openssl@1.1/lib/$lib";
 }

 # Windows only
```

**Comment by skaji** [comment]
Here is an issue tracker for mi6, neither GitHub Actions nor OpenSSL :)

**Comment by lizmat** [comment]
I develop on MacOS:

    $ raku -Ilib -MOpenSSL -e ""
    $

Aka, clean...

**Comment by skaji** [comment]
macos  "Run Tests" step in https://github.com/lizmat/API-Discogs/runs/912474996
```
Run prove6 -l t
t/01-basic.t .. No subtests run
All tests successful.

Test Summary Report
-------------------
t/01-basic.t (Wstat: 6 Tests: 0 Failed: 0)
Non-zero wait status: 6
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  78 wallclock secs
Result: FAILED
##[error]Process completed with exit code 2.
```

Note that `wait status: 6` means it was terminated by SIGABRT.

**Comment by skaji** [comment]
This is not an issue for mi6.

**Comment by lizmat** [comment]
True, but naive `App::Mi6` users that have this Github functionality added, and start getting emails for each test failure, *will* be bothering you about this again.  As they did not *ask* for this functionality.
